apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: fuqac0vm7-nodejs 
  janus-idp.io/tekton: fuqac0vm7-nodejs
  backstage.io/kubernetes-id: fuqac0vm7-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fuqac0vm7-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml